# Generated by Django 5.1.4 on 2024-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=155)),
                ('Item_prize', models.CharField(max_length=10)),
                ('Item_image', models.ImageField(default='default_image.jpg', upload_to='menu')),
            ],
        ),
    ]
